import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
type Profile={id:string;label:string;age:string};
type Content={id:string;title:string;intro:string;ending:string;quests:Array<{id:string;title:string;game?:string;lesson?:string}>;reviewRecord:{status:string;reviewer:string;note:string}};
const api=import.meta.env?.VITE_API_URL||'http://127.0.0.1:3000';
function App(){
    const [token,setToken]=useState(''),[role,setRole]=useState(''),[alias,setAlias]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[profiles,setProfiles]=useState<Profile[]>([]),[age,setAge]=useState('3-5'),[content,setContent]=useState<Content[]>([]),[reports,setReports]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]),[roomCode,setRoomCode]=useState(''),[invite,setInvite]=useState(''),[friend,setFriend]=useState(''),[share,setShare]=useState(''),[roomOwner,setRoomOwner]=useState(false),[tab,setTab]=useState('profiles');
    async function call(path:string,method='GET',body?:unknown,session=token){const r=await fetch(api+path,{method,headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.message||'Không thực hiện được');return data;}
    async function run(task:()=>Promise<void>){try{setMessage('');await task();}catch(e){setMessage((e as Error).message);}}
    async function login(){const result=await call('/sessions','POST',{alias,password});setToken(result.token);setRole(result.role);setPassword('');setProfiles(await call('/profiles','GET',undefined,result.token));}
    async function openRoom(profileId:string){const r=await call('/invites','POST',{profileId,...(friend?{invitation:friend}:roomCode?{roomCode}:{})});setRoomCode(r.roomCode);setInvite(r.ticket);setShare(r.friendInvitation||'');setRoomOwner(r.roomOwner===true);setMessage('Chỉ chia sẻ mã mời bạn với phụ huynh khác. Giữ riêng vé của hồ sơ trẻ.');}
    function launch(){const url=new URL(import.meta.env?.VITE_GAME_URL||'http://127.0.0.1:8080/');url.searchParams.set('server',import.meta.env?.VITE_SERVER_URL||'http://127.0.0.1:2567');url.hash=new URLSearchParams({room:roomCode,ticket:invite}).toString();window.open(url.href,'_blank','noopener,noreferrer');}
    async function editContent(c:Content){const title=window.prompt('Tên chương',c.title),intro=window.prompt('Hội thoại mở đầu',c.intro),ending=window.prompt('Hội thoại kết thúc',c.ending),note=window.prompt('Ghi chú chỉnh sửa (ít nhất 12 ký tự)');if(!title||!intro||!ending||!note)return;await call('/admin/content/'+c.id+'/text','PUT',{title,intro,ending,questTitles:Object.fromEntries(c.quests.map(q=>[q.id,q.title])),note});setContent(await call('/admin/content'));}
    async function exportContent(){const data=await call('/admin/content-export'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='lang-tri-thuc-content.json';a.click();URL.revokeObjectURL(url);}
    async function exportData(){const data=await call('/export'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='lang-tri-thuc-parent-export.json';a.click();URL.revokeObjectURL(url);}
    return <main><header><p className="eyebrow">LÀNG TRI THỨC</p><h1>Góc phụ huynh</h1><p>Hồ sơ dùng tên tự tạo. Không cần ngày sinh, trường học hoặc tên thật của trẻ.</p></header>
        {message&&<p role="status" className="notice">{message}</p>}
        {!token?<section><h2>Đăng nhập người lớn</h2><label>Bí danh tài khoản<input value={alias} onChange={e=>setAlias(e.target.value)} autoComplete="username" maxLength={40}/></label><label>Mật khẩu<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" maxLength={128}/></label><div className="actions"><button onClick={()=>run(login)}>Đăng nhập</button><button className="secondary" onClick={()=>run(async()=>{await call('/parents','POST',{alias,password});await login();})}>Tạo tài khoản phụ huynh</button></div><p>Mật khẩu tối thiểu 12 ký tự. Đây là bản thử; chưa mở dịch vụ công cộng cho trẻ.</p></section>:<>
        <nav><button onClick={()=>setTab('profiles')}>Hồ sơ và phòng riêng</button>{role==='admin'&&<><button onClick={()=>run(async()=>{setContent(await call('/admin/content'));setTab('content');})}>Nội dung</button><button onClick={()=>run(async()=>{setReports(await call('/admin/reports'));setTab('reports');})}>Báo cáo</button><button onClick={()=>run(async()=>{setAudit(await call('/admin/audit'));setTab('audit');})}>Nhật ký quản trị</button></>}<button className="secondary" onClick={()=>run(exportData)}>Xuất dữ liệu</button><button className="secondary" onClick={()=>run(async()=>{await call('/sessions','DELETE');setToken('');setInvite('');setShare('');setRoomOwner(false);})}>Đăng xuất</button></nav>
        {tab==='profiles'&&<section><h2>Hồ sơ của trẻ</h2><label>Mức học<select value={age} onChange={e=>setAge(e.target.value)}><option>3-5</option><option>6-8</option><option>9-11</option></select></label><button onClick={()=>run(async()=>{await call('/profiles','POST',{age});setProfiles(await call('/profiles'));})}>Thêm hồ sơ</button><div className="cards">{profiles.map(p=><article key={p.id}><h3>{p.label}</h3><p>Mức học {p.age} tuổi</p><button onClick={()=>run(()=>openRoom(p.id))}>Cho phép vào phòng riêng</button><button className="secondary" onClick={()=>run(async()=>{const result=await call('/profiles/'+p.id+'/progress');setMessage(`Bản sao tiến độ: revision ${result.revision}. Kết quả online xác nhận: ${result.receipts.length}.`);})}>Xem tiến độ</button><button className="danger" onClick={()=>{if(window.confirm('Xóa hồ sơ và tiến độ này?'))void run(async()=>{await call('/profiles/'+p.id,'DELETE');setProfiles(await call('/profiles'));});}}>Xóa hồ sơ</button></article>)}</div><label>Mã phòng đã được người lớn chia sẻ<input value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())} maxLength={8}/></label><label>Mã mời bạn do phụ huynh chủ phòng cấp<input value={friend} onChange={e=>setFriend(e.target.value)} maxLength={64}/></label>{roomOwner&&<div className="notice"><label>Mã mời dành cho phụ huynh bạn<input readOnly value={share}/></label><button onClick={()=>run(async()=>{await call("/rooms/"+roomCode,"PUT",{locked:true});setMessage("Đã khóa phòng với người mới.");})}>Khóa phòng</button><button onClick={()=>run(async()=>{await call("/rooms/"+roomCode,"PUT",{locked:false});setMessage("Đã mở phòng cho lời mời còn hạn.");})}>Mở khóa</button></div>}{invite&&<div className="notice"><p>Phòng {roomCode}. Vé chỉ dùng cho hồ sơ đã chọn; không công bố lên mạng.</p><button onClick={launch}>Mở làng cho hồ sơ này</button></div>}<button className="danger" onClick={()=>{if(window.confirm('Xóa toàn bộ tài khoản, hồ sơ và tiến độ?'))void run(async()=>{await call('/parents/me','DELETE');setToken('');setInvite('');setShare('');setRoomOwner(false);});}}>Xóa tài khoản và dữ liệu</button></section>}
        {tab==='content'&&<section><button onClick={()=>run(exportContent)}>Xuất gói nội dung</button><h2>Nội dung cốt truyện</h2><p>Chỉ người biên tập đã kiểm nội dung và nguồn mới chuyển sang approved. Trạng thái mặc định là draft.</p>{content.map(c=><article key={c.id}><h3>{c.id} • {c.title}</h3><button onClick={()=>run(()=>editContent(c))}>Sửa hội thoại chương</button><p>{c.intro}</p><ul>{c.quests.map(q=><li key={q.id}>{q.id}: {q.title} {q.game||q.lesson||''}</li>)}</ul><p>{c.ending}</p><p>Trạng thái: {c.reviewRecord.status} • {c.reviewRecord.reviewer}</p><div className="actions">{['draft','reviewed','approved'].map(status=><button key={status} className="secondary" onClick={()=>{const note=window.prompt('Ghi chú biên tập, nguồn và phạm vi đã kiểm (ít nhất 12 ký tự):');if(note)void run(async()=>{await call('/admin/content/'+c.id,'PUT',{status,note});setContent(await call('/admin/content'));});}}>{status}</button>)}</div></article>)}</section>}
        {tab==='reports'&&<section><h2>Hàng đợi báo cáo</h2>{reports.length===0?<p>Chưa có báo cáo.</p>:reports.map(r=><article key={r.id}><p>Lý do: {r.reason} • {r.status}</p><p>Mã báo cáo: {r.id}</p>{r.status==='open'&&<button onClick={()=>run(async()=>{await call('/admin/reports/'+r.id+'/resolve','PUT');setReports(await call('/admin/reports'));})}>Đánh dấu đã xử lý</button>}</article>)}</section>}
        {tab==='audit'&&<section><h2>Nhật ký quản trị</h2><ul>{audit.map((a,i)=><li key={i}>{new Date(a.created).toLocaleString('vi-VN')} • {a.action} • {a.entity}</li>)}</ul></section>}
        </>}
        <footer>Không có chat tự do hoặc voice chat. Quyết định biên tập và xử lý báo cáo cần người lớn phụ trách.</footer></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
