import Fastify,{FastifyRequest} from 'fastify';
import cors from '@fastify/cors';
import {randomBytes,randomUUID,createHmac,timingSafeEqual} from 'node:crypto';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {BackendData,ParentRecord,Repository,SqliteRepository,PostgresRepository} from './Store';
import {digest,passwordHash,verifyPassword,signTicket} from './Auth';
import {CampaignEngine} from '../../game-client/assets/scripts/world/CampaignEngine';
import {chapters} from '../../game-client/assets/scripts/world/CampaignContent';
import {ChapterOneProgress} from '../../game-client/assets/scripts/world/ChapterOneProgress';
export interface ApiOptions {store?:Repository;roomSecret?:string;adminPassword?:string;origin?:string[]}
const object=(properties:Record<string,unknown>,required:string[]=Object.keys(properties))=>({type:'object',additionalProperties:false,properties,required});
const str={type:'string',minLength:1,maxLength:200},age={type:'string',enum:['3-5','6-8','9-11']};
export async function createApi(options:ApiOptions={}){
    const store=options.store??(process.env.DATABASE_URL?new PostgresRepository(process.env.DATABASE_URL):new SqliteRepository(process.env.SQLITE_PATH||fileURLToPath(new URL('../.data/game.sqlite',import.meta.url))));
    const roomSecret=options.roomSecret||process.env.ROOM_SECRET;if(!roomSecret||roomSecret.length<32)throw Error('ROOM_SECRET must have at least 32 characters');
    const app=Fastify({bodyLimit:65536,logger:false});await app.register(cors,{origin:options.origin||(process.env.ALLOWED_ORIGINS?.split(',')??['http://127.0.0.1:5173','http://localhost:5173','http://127.0.0.1:8080']),methods:['GET','POST','PUT','DELETE'],allowedHeaders:['Content-Type','Authorization']});
    const rates=new Map<string,{count:number;time:number}>();
    app.addHook('preHandler',async(req,reply)=>{const signature=req.headers['x-service-signature'];if(req.url.startsWith('/internal/')&&typeof signature==='string'){const expected=createHmac('sha256',roomSecret).update(JSON.stringify(req.body)).digest('hex'),a=Buffer.from(signature),b=Buffer.from(expected);if(a.length===b.length&&timingSafeEqual(a,b))return;}const now=Date.now(),key=req.ip,r=rates.get(key);if(!r||now-r.time>60000)rates.set(key,{count:1,time:now});else if(++r.count>120){reply.code(429);throw Error('Too many requests');}if(rates.size>2000)for(const [id,r] of rates)if(now-r.time>60000)rates.delete(id);});
    app.addHook('onClose',async()=>store.close());
    if(options.adminPassword){if(options.adminPassword.length<12)throw Error('Admin password too short');await store.transaction(d=>{if(!Object.values(d.parents).some(p=>p.role==='admin')){const id=randomUUID();d.parents[id]={id,alias:'admin',passwordHash:passwordHash(options.adminPassword!),role:'admin'};}});}
    const auth=async(req:FastifyRequest,admin=false):Promise<ParentRecord>=>store.transaction(d=>{
        const token=req.headers.authorization?.replace(/^Bearer /,''),s=token?d.sessions[digest(token)]:null,p=s&&s.expires>Date.now()?d.parents[s.parentId]:null;if(!p||admin&&p.role!=='admin')throw Object.assign(Error('Unauthorized'),{statusCode:401});return p;
    });
    const owned=(d:BackendData,parentId:string,id:string)=>{const p=d.profiles[id];if(!p||p.parentId!==parentId)throw Object.assign(Error('Not found'),{statusCode:404});return p;};
    app.get('/health',async()=>({ok:true,storage:process.env.DATABASE_URL?'postgresql':'sqlite-local',prototype:true}));
    app.post<{Body:{alias:string;password:string}}>('/parents',{schema:{body:object({alias:{type:'string',minLength:3,maxLength:40,pattern:'^[a-zA-Z0-9_-]+$'},password:{type:'string',minLength:12,maxLength:128}})}},async(req,reply)=>{
        const parent=await store.transaction(d=>{if(req.body.alias.toLowerCase()==='admin'||Object.values(d.parents).some(p=>p.alias===req.body.alias))throw Object.assign(Error('Alias unavailable'),{statusCode:409});const id=randomUUID(),p={id,alias:req.body.alias,passwordHash:passwordHash(req.body.password),role:'parent' as const};d.parents[id]=p;return {id,alias:p.alias};});return reply.code(201).send(parent);
    });
    app.post<{Body:{alias:string;password:string}}>('/sessions',{schema:{body:object({alias:str,password:{type:'string',minLength:1,maxLength:128}})}},async req=>store.transaction(d=>{
        const p=Object.values(d.parents).find(p=>p.alias===req.body.alias);if(!p||!verifyPassword(req.body.password,p.passwordHash))throw Object.assign(Error('Invalid credentials'),{statusCode:401});
        const now=Date.now();for(const [k,s] of Object.entries(d.sessions))if(s.expires<now)delete d.sessions[k];const token=randomBytes(32).toString('base64url');d.sessions[digest(token)]={parentId:p.id,expires:now+8*3600000};return {token,role:p.role,expires:now+8*3600000};
    }));
    app.delete('/sessions',async req=>{await auth(req);return store.transaction(d=>{delete d.sessions[digest(req.headers.authorization!.replace(/^Bearer /,''))];return {ok:true};});});
    app.get('/profiles',async req=>{const p=await auth(req);return store.transaction(d=>Object.values(d.profiles).filter(c=>c.parentId===p.id));});
    app.post<{Body:{age:string}}>('/profiles',{schema:{body:object({age})}},async(req,reply)=>{const p=await auth(req);const result=await store.transaction(d=>{const count=Object.values(d.profiles).filter(c=>c.parentId===p.id).length;if(count>=8)throw Object.assign(Error('Profile limit'),{statusCode:409});const id=randomUUID(),profile={id,parentId:p.id,label:'Bé '+(count+1),age:req.body.age as any,blocked:[]};d.profiles[id]=profile;return profile;});return reply.code(201).send(result);});
    app.get<{Params:{id:string}}>('/profiles/:id/progress',async req=>{const p=await auth(req);return store.transaction(d=>{owned(d,p.id,req.params.id);return d.progress[req.params.id]??{revision:0,data:null,receipts:[]};});});
    app.put<{Params:{id:string};Body:{revision:number;campaign:string}}>('/profiles/:id/progress',{schema:{body:object({revision:{type:'integer',minimum:0},campaign:{type:'string',maxLength:48000}})}},async req=>{const p=await auth(req);return store.transaction(d=>{owned(d,p.id,req.params.id);const existing=d.progress[req.params.id]??{revision:0,data:null,receipts:[]};if(existing.revision!==req.body.revision)throw Object.assign(Error('Revision conflict'),{statusCode:409});const engine=new CampaignEngine();if(!engine.restore(req.body.campaign))throw Object.assign(Error('Invalid progress'),{statusCode:400});
        // Local progress is a backup, not an authoritative online reward claim.
        const result={...existing,revision:existing.revision+1,data:engine.data,receipts:existing.receipts};d.progress[req.params.id]=result;return result;});});
    app.delete<{Params:{id:string}}>('/profiles/:id',async req=>{const p=await auth(req);return store.transaction(d=>{owned(d,p.id,req.params.id);delete d.profiles[req.params.id];delete d.progress[req.params.id];d.results=d.results.filter(id=>!id.startsWith(req.params.id+':'));for(const profile of Object.values(d.profiles))profile.blocked=profile.blocked.filter(id=>id!==req.params.id);d.reports=d.reports.filter(r=>r.reporter!==req.params.id&&r.target!==req.params.id);return {ok:true};});});
    app.get('/export',async req=>{const p=await auth(req);return store.transaction(d=>{const profiles=Object.values(d.profiles).filter(c=>c.parentId===p.id);return {parent:{id:p.id,alias:p.alias},profiles,progress:Object.fromEntries(profiles.map(c=>[c.id,d.progress[c.id]??null]))};});});
    app.delete('/parents/me',async req=>{const p=await auth(req);return store.transaction(d=>{const ids=Object.values(d.profiles).filter(c=>c.parentId===p.id).map(c=>c.id);for(const id of ids){delete d.profiles[id];delete d.progress[id];}d.reports=d.reports.filter(r=>!ids.includes(r.reporter)&&!ids.includes(r.target));d.results=d.results.filter(result=>!ids.some(id=>result.startsWith(id+':')));for(const child of Object.values(d.profiles))child.blocked=child.blocked.filter(id=>!ids.includes(id));for(const [code,room] of Object.entries(d.rooms)){room.allowedParents=room.allowedParents.filter(id=>id!==p.id);if(room.ownerId===p.id){delete d.rooms[code];for(const [key,invite] of Object.entries(d.invitations))if(invite.roomCode===code)delete d.invitations[key];}}for(const [k,s] of Object.entries(d.sessions))if(s.parentId===p.id)delete d.sessions[k];delete d.parents[p.id];return {ok:true};});});
    app.post<{Body:{profileId:string;roomCode?:string;invitation?:string}}>('/invites',{schema:{body:object({profileId:str,roomCode:{type:'string',pattern:'^[A-Z0-9]{8}$'},invitation:{type:'string',minLength:20,maxLength:100}},['profileId'])}},async req=>{const p=await auth(req);return store.transaction(d=>{
        const profile=owned(d,p.id,req.body.profileId);let roomCode=req.body.roomCode,friendInvitation:string|undefined;
        if(req.body.invitation){const invite=d.invitations[digest(req.body.invitation)];if(!invite||invite.expires<Date.now()||invite.remaining<=0)throw Object.assign(Error('Invitation expired'),{statusCode:403});roomCode=invite.roomCode;const room=d.rooms[roomCode];if(!room||room.locked)throw Object.assign(Error('Room unavailable'),{statusCode:403});if(!room.allowedParents.includes(p.id)){room.allowedParents.push(p.id);invite.remaining--;}}
        if(!roomCode){roomCode=randomBytes(4).toString('hex').toUpperCase();d.rooms[roomCode]={ownerId:p.id,allowedParents:[p.id],expires:Date.now()+24*3600000,locked:false};friendInvitation=randomBytes(24).toString('base64url');d.invitations[digest(friendInvitation)]={roomCode,expires:Date.now()+15*60000,remaining:3};}
        const room=d.rooms[roomCode];if(!room||room.expires<Date.now()||room.locked||!room.allowedParents.includes(p.id))throw Object.assign(Error('Room access denied'),{statusCode:403});
        const roomOwner=d.rooms[roomCode].ownerId===p.id;for(const [key,invite] of Object.entries(d.invitations))if(invite.expires<Date.now())delete d.invitations[key];if(roomOwner&&!friendInvitation){friendInvitation=randomBytes(24).toString('base64url');d.invitations[digest(friendInvitation)]={roomCode,expires:Date.now()+15*60000,remaining:3};}const expires=Date.now()+15*60000;return {roomCode,expires,friendInvitation,roomOwner,ticket:signTicket({profileId:profile.id,roomCode,age:profile.age,expires,consent:true},roomSecret)};
    });});
    app.put<{Params:{code:string};Body:{locked:boolean}}>('/rooms/:code',{schema:{body:object({locked:{type:'boolean'}})}},async req=>{const p=await auth(req);return store.transaction(d=>{const room=d.rooms[req.params.code];if(!room||room.ownerId!==p.id)throw Object.assign(Error('Not found'),{statusCode:404});room.locked=req.body.locked;return {ok:true};});});
    app.get('/admin/content',async req=>{await auth(req,true);return store.transaction(d=>chapters.map(c=>({...c,...d.content[c.id],quests:c.quests.map(q=>({...q,title:d.content[c.id]?.questTitles[q.id]??q.title})),reviewRecord:d.review[c.id]??{status:'draft',reviewer:'',note:''}})));});
    app.put<{Params:{id:string};Body:{status:'draft'|'reviewed'|'approved';note:string}}>('/admin/content/:id',{schema:{body:object({status:{type:'string',enum:['draft','reviewed','approved']},note:{type:'string',minLength:12,maxLength:500}})}},async req=>{const p=await auth(req,true);if(!chapters.some(c=>c.id===req.params.id))throw Object.assign(Error('Not found'),{statusCode:404});return store.transaction(d=>{if(req.body.status==='approved'&&d.review[req.params.id]?.status!=='reviewed')throw Object.assign(Error('Review before approval'),{statusCode:409});d.review[req.params.id]={status:req.body.status,reviewer:p.alias,note:req.body.note,updated:Date.now()};d.audit.push({actor:p.id,action:'content.'+req.body.status,entity:req.params.id,created:Date.now()});return d.review[req.params.id];});});
    app.get('/admin/content-export',async req=>{await auth(req,true);return store.transaction(d=>({version:1,chapters:chapters.map(c=>({...c,...d.content[c.id],quests:c.quests.map(q=>({...q,title:d.content[c.id]?.questTitles[q.id]??q.title})),reviewRecord:d.review[c.id]??{status:'draft',reviewer:'',note:''}}))}));});
    app.put<{Params:{id:string};Body:{title:string;intro:string;ending:string;questTitles:Record<string,string>;note:string}}>('/admin/content/:id/text',{schema:{body:object({title:{type:'string',minLength:1,maxLength:120},intro:{type:'string',minLength:1,maxLength:800},ending:{type:'string',minLength:1,maxLength:800},questTitles:{type:'object',maxProperties:8,additionalProperties:{type:'string',minLength:1,maxLength:120}},note:{type:'string',minLength:12,maxLength:500}})}},async req=>{const p=await auth(req,true),c=chapters.find(c=>c.id===req.params.id);if(!c||Object.keys(req.body.questTitles).some(id=>!c.quests.some(q=>q.id===id)))throw Object.assign(Error('Invalid chapter text'),{statusCode:400});return store.transaction(d=>{const {note,...text}=req.body;d.content[c.id]=text;d.review[c.id]={status:'draft',reviewer:p.alias,note,updated:Date.now()};d.audit.push({actor:p.id,action:'content.edit',entity:c.id,created:Date.now()});return {ok:true};});});
    app.get('/admin/reports',async req=>{await auth(req,true);return store.transaction(d=>d.reports);});
    app.put<{Params:{id:string}}>('/admin/reports/:id/resolve',async req=>{const p=await auth(req,true);return store.transaction(d=>{const r=d.reports.find(r=>r.id===req.params.id);if(!r)throw Object.assign(Error('Not found'),{statusCode:404});r.status='resolved';d.audit.push({actor:p.id,action:'report.resolve',entity:r.id,created:Date.now()});return {ok:true};});});
    app.get('/admin/audit',async req=>{await auth(req,true);return store.transaction(d=>d.audit.slice(-200));});
    const service=async(req:FastifyRequest)=>{const signature=req.headers['x-service-signature'];if(typeof signature!=='string')throw Object.assign(Error('Unauthorized'),{statusCode:401});const raw=JSON.stringify(req.body),expected=createHmac('sha256',roomSecret).update(raw).digest('hex'),a=Buffer.from(signature),b=Buffer.from(expected);if(a.length!==b.length||!timingSafeEqual(a,b))throw Object.assign(Error('Unauthorized'),{statusCode:401});};
    app.post<{Body:{profileId:string;roomCode:string;existing?:boolean}}>('/internal/profile',{schema:{body:object({profileId:str,roomCode:str,existing:{type:'boolean'}},['profileId','roomCode'])}},async req=>{await service(req);return store.transaction(d=>{const p=d.profiles[req.body.profileId],room=d.rooms[req.body.roomCode];if(!p||!room||room.locked&&!req.body.existing||room.expires<Date.now()||!room.allowedParents.includes(p.parentId))throw Object.assign(Error('Room access denied'),{statusCode:403});return {...p,roomOwner:room.ownerId===p.parentId,trusted:d.progress[p.id]?.trusted??null};});});
    app.post<{Body:{profileId:string;first:string;campaign:string}}>('/internal/progress',{schema:{body:object({profileId:str,first:{type:'string',maxLength:4000},campaign:{type:'string',maxLength:48000}})}},async req=>{await service(req);return store.transaction(d=>{if(!d.profiles[req.body.profileId])throw Object.assign(Error('Not found'),{statusCode:404});const first=new ChapterOneProgress(),campaign=new CampaignEngine();if(!first.restore(req.body.first)||!campaign.restore(req.body.campaign))throw Object.assign(Error('Invalid trusted state'),{statusCode:400});campaign.syncChapterOne(first.data);const p=d.progress[req.body.profileId]??{revision:0,data:null,receipts:[]};p.trusted={chapterOne:first.data,campaign:campaign.data};p.revision++;d.progress[req.body.profileId]=p;return {ok:true};});});
    app.post<{Body:{profileId:string;target:string;reason:string}}>('/internal/report',{schema:{body:object({profileId:str,target:str,reason:{type:'string',enum:['spam','uncomfortable','other']}})}},async req=>{await service(req);return store.transaction(d=>{if(!d.profiles[req.body.profileId])throw Object.assign(Error('Unknown profile'),{statusCode:404});if(d.reports.filter(r=>r.reporter===req.body.profileId&&Date.now()-r.created<60000).length>=5)throw Object.assign(Error('Report rate limit'),{statusCode:429});const report={id:randomUUID(),reporter:req.body.profileId,target:req.body.target,reason:req.body.reason,created:Date.now(),status:'open' as const};d.reports.push(report);return {ok:true};});});
    app.post<{Body:{profileId:string;target:string}}>('/internal/block',{schema:{body:object({profileId:str,target:str})}},async req=>{await service(req);return store.transaction(d=>{const p=d.profiles[req.body.profileId];if(!p)throw Object.assign(Error('Not found'),{statusCode:404});if(!p.blocked.includes(req.body.target)&&p.blocked.length<100)p.blocked.push(req.body.target);return {ok:true};});});
    app.post<{Body:{profileId:string;gameId:string;attemptId:string}}>('/internal/result',{schema:{body:object({profileId:str,gameId:str,attemptId:str})}},async req=>{await service(req);return store.transaction(d=>{if(!d.profiles[req.body.profileId])throw Object.assign(Error('Not found'),{statusCode:404});const id=req.body.profileId+':'+req.body.attemptId;if(d.results.includes(id))return {ok:true,duplicate:true};d.results.push(id);const p=d.progress[req.body.profileId]??{revision:0,data:null,receipts:[]};p.receipts.push('game.'+req.body.gameId+'.'+req.body.attemptId);p.revision++;d.progress[req.body.profileId]=p;return {ok:true};});});
    return app;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){createApi({adminPassword:process.env.ADMIN_BOOTSTRAP_PASSWORD}).then(app=>app.listen({host:process.env.HOST||'127.0.0.1',port:Number(process.env.API_PORT||3000)})).then(address=>console.log('Parent API: '+address)).catch(e=>{console.error(e.message);process.exitCode=1;});}
