const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{chromium}=require('playwright');
const output=path.resolve(__dirname,'../temp/admin-qa');fs.mkdirSync(output,{recursive:true});
(async()=>{
 // Isolated in-memory API: editorial QA must never alter the user's real content/reviews.
 const script="const {createApi}=await import('./apps/backend/dist/main.js');const {SqliteRepository}=await import('./apps/backend/dist/Store.js');const app=await createApi({store:new SqliteRepository(),roomSecret:'admin-browser-integration-only-secret',adminPassword:'AdminBrowserFixture123!',origin:['http://127.0.0.1:35173']});await app.listen({host:'127.0.0.1',port:33001});console.log('ADMIN_QA_READY');";
 const server=spawn(process.execPath,['--input-type=module','-e',script],{cwd:path.resolve(__dirname,'../../..'),windowsHide:true,stdio:['ignore','pipe','pipe']});
 let browser,page;try{
  await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Admin QA API timeout')),10000);server.stdout.on('data',data=>{if(String(data).includes('ADMIN_QA_READY')){clearTimeout(timer);resolve();}});server.on('error',reject);server.once('exit',code=>reject(Error('QA API exited '+code)));});
  browser=await chromium.launch({executablePath:require('../../../tools/browser-path.cjs')(),headless:true});page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.route('http://127.0.0.1:33000/**',async route=>{const response=await route.fetch({url:route.request().url().replace(':33000',':33001')});await route.fulfill({response});});
  await page.goto('http://127.0.0.1:35173/');await page.getByLabel('Bí danh tài khoản').fill('admin');await page.getByLabel('Mật khẩu',{exact:true}).fill('AdminBrowserFixture123!');await page.getByRole('button',{name:'Đăng nhập',exact:true}).click();
  await page.getByRole('button',{name:'Nội dung',exact:true}).click();await page.getByRole('button',{name:'Sửa hội thoại chương'}).first().click();
  await page.getByLabel('Tên chương',{exact:true}).fill('Chương QA có dấu Việt');await page.getByLabel('Tên nhiệm vụ 1',{exact:true}).fill('Nhiệm vụ QA');await page.getByLabel('Ghi chú chỉnh sửa',{exact:true}).fill('Fixture browser editorial validation');await page.getByRole('button',{name:'Lưu chương',exact:true}).click();await page.getByRole('heading',{name:/ch01.*Chương QA có dấu Việt/}).waitFor();
  await page.getByRole('button',{name:'Bài học',exact:true}).click();await page.getByRole('button',{name:'Sửa bài học',exact:true}).first().click();await page.getByLabel('Câu hỏi',{exact:true}).fill('Câu hỏi QA tiếng Việt?');await page.getByLabel('Ghi chú biên tập',{exact:true}).fill('Fixture lesson browser validation');await page.getByRole('button',{name:'Lưu bài học',exact:true}).click();await page.getByRole('heading',{name:'Câu hỏi QA tiếng Việt?'}).waitFor();
  const article=page.locator('article').filter({has:page.getByRole('heading',{name:'Câu hỏi QA tiếng Việt?'})});page.once('dialog',d=>d.accept('Fixture human review simulation only'));await article.getByRole('button',{name:'reviewed',exact:true}).click();await article.getByText('Trạng thái: reviewed',{exact:true}).waitFor();
  await page.screenshot({path:path.join(output,'lessons.png')});await page.getByRole('button',{name:'NPC và tài nguyên',exact:true}).click();await page.getByRole('button',{name:/Sửa NPC/}).first().click();await page.getByLabel('Tên NPC',{exact:true}).fill('NPC QA Việt');await page.getByLabel('Ghi chú kiểm tra',{exact:true}).fill('Fixture NPC browser validation');await page.getByRole('button',{name:'Lưu danh mục',exact:true}).click();await page.getByRole('heading',{name:'NPC QA Việt',exact:true}).waitFor();
  await page.getByRole('button',{name:'Sửa nguồn child',exact:true}).click();await page.getByLabel('Tên tài nguyên',{exact:true}).fill('Avatar QA');await page.getByLabel('Ghi chú kiểm tra',{exact:true}).fill('Fixture provenance browser validation');await page.getByRole('button',{name:'Lưu danh mục',exact:true}).click();await page.getByRole('heading',{name:'Avatar QA',exact:true}).waitFor();await page.screenshot({path:path.join(output,'catalog.png')});
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Xuất gói nội dung',exact:true}).click();const file=await download;await file.saveAs(path.join(output,'fixture-export.json'));const pack=JSON.parse(fs.readFileSync(path.join(output,'fixture-export.json'),'utf8'));assert.equal(pack.chapters[0].title,'Chương QA có dấu Việt');assert.equal(pack.lessons.length,90);assert.equal(pack.npcs[0].name,'NPC QA Việt');assert.equal(pack.assets.length,24);assert.deepEqual(errors,[]);
  const result={chapterEditor:true,questTitles:true,lessonEditor:true,review:true,npcEditor:true,assetMetadata:true,fullExport:true,isolatedDatabase:true,errors};fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
 }catch(error){if(page){await page.screenshot({path:path.join(output,'failure.png')});console.error(await page.locator('body').innerText());}throw error;}finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
