const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright');
const origin=process.env.GAME_WEB_URL||'http://127.0.0.1:38080/',output=path.resolve(__dirname,'../temp/zoom-qa');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:require('../../../tools/browser-path.cjs')(),headless:true,args:['--enable-webgl','--use-angle=d3d11']}),errors=[];
 try{for(const mobile of [false,true]){
  const options=mobile?{viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36'}:{viewport:{width:1280,height:720}};
  if(process.env.STAGING_ACCESS_FILE){const raw=fs.readFileSync(process.env.STAGING_ACCESS_FILE,'utf8');options.httpCredentials={username:'staging',password:/^Preview password: (.+)$/m.exec(raw)[1],origin:new URL(origin).origin};}
  const context=await browser.newContext(options),page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));
  async function boot(){await page.waitForFunction(()=>!!window.System);await page.evaluate(async()=>window.cc=await System.import('cc'));await page.waitForFunction(()=>cc.director.getScene()?.getChildByName('Canvas')?.getComponent('VillageBootstrap')?.assetsReady,undefined,{timeout:120000});await page.evaluate(()=>window.village=cc.director.getScene().getChildByName('Canvas').getComponent('VillageBootstrap'));}
  await page.goto(origin);await boot();
  async function point(id,kind='root'){return page.evaluate(({id,kind})=>{const b=village,n=kind==='chapter'?b.chapter.node.getChildByName(id):kind==='hub'?b.hub.node.getChildByName(id):b.root.getChildByName(id),world=n.getComponent(cc.UITransform).convertToWorldSpaceAR(new cc.Vec3()),s=b.node.getComponent(cc.Canvas).cameraComponent.worldToScreen(world),c=cc.game.canvas,r=c.getBoundingClientRect();return{x:r.left+s.x/c.width*r.width,y:r.top+(c.height-s.y)/c.height*r.height};},{id,kind});}
  async function tap(id,kind='root'){const p=await point(id,kind);if(mobile)await page.touchscreen.tap(p.x,p.y);else await page.mouse.click(p.x,p.y);await page.waitForTimeout(150);}
  async function box(id){return page.evaluate(id=>{const b=village,n=b.root.getChildByName(id),t=n.getComponent(cc.UITransform),camera=b.node.getComponent(cc.Canvas).cameraComponent,c=cc.game.canvas,r=c.getBoundingClientRect(),a=camera.worldToScreen(t.convertToWorldSpaceAR(new cc.Vec3(-t.width/2,-t.height/2))),z=camera.worldToScreen(t.convertToWorldSpaceAR(new cc.Vec3(t.width/2,t.height/2)));return {x:r.left+a.x/c.width*r.width,y:r.top+(c.height-z.y)/c.height*r.height,w:(z.x-a.x)/c.width*r.width,h:(z.y-a.y)/c.height*r.height};},id);}
  await tap('Continue','chapter');await page.waitForFunction(()=>!village.modalActive);
  assert.equal(await page.evaluate(()=>village.childSprite.node.parent.scale.x),.65);assert.equal(await page.evaluate(()=>village.farmer.node.getChildByName('FarmerSprite').scale.x),.65);assert.equal(await page.evaluate(()=>village.chapter.elder.getChildByName('ElderSprite').scale.x),.65);
  const saved=await page.evaluate(()=>JSON.stringify(village.hub.campaign.data)),position=await page.evaluate(()=>({...village.player.position})),hud=await box('OpenParent');
  await tap('ZoomIn');assert.ok(await page.evaluate(()=>village.zoom.value>1));assert.deepEqual(await page.evaluate(()=>({...village.player.position})),position);assert.equal(await page.evaluate(()=>JSON.stringify(village.hub.campaign.data)),saved);const next=await box('OpenParent');assert.ok(Math.abs(next.w-hud.w)<.1);await tap('ZoomReset');assert.equal(await page.evaluate(()=>village.zoom.value),1);
  if(!mobile){
   await page.mouse.move(600,440);for(let i=0;i<4;i++){await page.mouse.wheel(0,-500);await page.waitForTimeout(80);}assert.equal(await page.evaluate(()=>village.zoom.value),1.8);
   for(let i=0;i<4;i++){await page.mouse.wheel(0,500);await page.waitForTimeout(80);}assert.equal(await page.evaluate(()=>village.zoom.value),.6);
   const goal=await page.evaluate(()=>{const b=village,p={x:32,y:-656},w=b.world.getComponent(cc.UITransform).convertToWorldSpaceAR(new cc.Vec3(p.x,p.y)),s=b.node.getComponent(cc.Canvas).cameraComponent.worldToScreen(w),c=cc.game.canvas,r=c.getBoundingClientRect();return{x:r.left+s.x/c.width*r.width,y:r.top+(c.height-s.y)/c.height*r.height};});await page.mouse.click(goal.x,goal.y);await page.waitForFunction(()=>!village.player.hasPath&&Math.abs(village.player.position.x-32)<1&&Math.abs(village.player.position.y+656)<1);
   await tap('OpenJournal');assert.equal(await page.evaluate(()=>village.zoomButtons.every(n=>!n.active)),true);await page.mouse.wheel(0,-500);await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>village.zoom.value),.6);await tap('HubClose','hub');
   await page.waitForFunction(()=>localStorage.getItem('lang-tri-thuc.view-zoom.v1')==='0.6');await page.reload();await boot();assert.equal(await page.evaluate(()=>village.zoom.value),.6);await tap('ZoomReset');
   await page.setViewportSize({width:1917,height:918});await page.waitForTimeout(300);await page.screenshot({path:path.join(output,'scale-desktop.png')});
  }else{
   const cdp=await context.newCDPSession(page);async function pinch(start,end){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:start[0],y:430,id:1},{x:start[1],y:430,id:2}]});await page.waitForFunction(()=>!!village.pinchIds,undefined,{timeout:4000}).catch(async()=>{throw Error(JSON.stringify(await page.evaluate(()=>({touches:[...village.touches],modal:village.modalActive,stick:village.stickId,multi:cc.macro.ENABLE_MULTI_TOUCH}))));});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:end[0],y:430,id:1},{x:end[1],y:430,id:2}]});await page.waitForTimeout(160);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>!village.pinchIds);}
   await pinch([150,240],[80,310]);assert.equal(await page.evaluate(()=>village.zoom.value),1.8);await pinch([80,310],[180,210]);assert.equal(await page.evaluate(()=>village.zoom.value),.6);assert.equal(await page.evaluate(()=>village.player.hasPath),false);assert.deepEqual(await page.evaluate(()=>({...village.player.position})),position);
   const stick=await point('Joystick');await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...stick,id:3}]});await page.waitForFunction(()=>village.stickId!==null);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...stick,id:3},{x:260,y:430,id:4}]});assert.equal(await page.evaluate(()=>village.pinchIds===undefined),true);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await tap('ZoomReset');
   for(const id of ['ZoomOut','ZoomReset','ZoomIn']){const b=await box(id);assert.ok(b.w>=44&&b.h>=44);assert.ok(b.x>=0&&b.x+b.w<=390.1);}await page.screenshot({path:path.join(output,'zoom-mobile.png')});
   await page.setViewportSize({width:844,height:390});await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>village.zoom.value),1);for(const id of ['ZoomOut','ZoomReset','ZoomIn']){const b=await box(id);assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=844.1&&b.y+b.h<=390.1);}await tap('ZoomIn');assert.ok(await page.evaluate(()=>village.zoom.value>1));await page.screenshot({path:path.join(output,'zoom-landscape.png')});
  }
  await context.close();
 }assert.deepEqual(errors,[]);const report={actorScale:.65,wheel:true,buttons:true,pinch:true,limits:[.6,1.8],fixedHud:true,clickToMoveAtZoom:true,modalBlocksZoom:true,reloadPreference:true,joystickOwnership:true,portraitLandscape:true,errors};fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
